services:
  redis:
    image: redis:7-alpine
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    networks:
      - soliant-mock-api

  app:
    image: ${IMAGE_NAME}:latest
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      REDIS_HOST: "redis:6379"
      ENV: "PROD"
      PORT: "${PORT}"
    depends_on:
      - redis
    networks:
      - soliant-mock-api

networks:
  soliant-mock-api:
    driver: bridge

volumes:
  redis-data:
