name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.SERVER_IP }}"
          username: "${{ secrets.SERVER_USER }}"
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          script: |
            cd /home/ac/Desktop/soliant-mock-api/soliant-mock-api
            export PATH=$PATH:/usr/libexec/docker/cli-plugins
            export GH_TOKEN="${{ secrets.GH_TOKEN }}"
            export PORT="3030"
            export ENV="PROD"

            git pull origin develop --no-rebase

            docker-compose stop
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
