package notifications

const mockUserUUID = "mock-user-uuid"

// Seed returns the default list of notifications used to populate an empty
// store.
func Seed() []Notification {
	return []Notification{
		{
			UUID:       "1",
			UserUUID:   mockUserUUID,
			Type:       "shift_end",
			Title:      "Your shift is ending",
			Body:       "Don't forget to check out",
			CreatedAt:  "2026-04-24T12:25:00Z",
			UpdatedAt:  "2026-04-24T12:25:00Z",
			IsRead:     false,
			ActionText: "Check out",
			Data:       map[string]any{},
		},
		{
			UUID:       "2",
			UserUUID:   mockUserUUID,
			Type:       "check_in_open",
			Title:      "Check-in open",
			Body:       "You can check in to your shift now",
			CreatedAt:  "2026-04-24T03:30:00Z",
			UpdatedAt:  "2026-04-24T03:30:00Z",
			IsRead:     false,
			ActionText: "Check in",
			Data:       map[string]any{},
		},
		{
			UUID:       "3",
			UserUUID:   mockUserUUID,
			Type:       "shift_accepted",
			Title:      "Shift accepted",
			Body:       "Your shift request has been accepted",
			CreatedAt:  "2026-04-24T02:30:00Z",
			UpdatedAt:  "2026-04-24T02:30:00Z",
			IsRead:     true,
			ActionText: "View details",
			Data:       map[string]any{},
		},
		{
			UUID:       "4",
			UserUUID:   mockUserUUID,
			Type:       "new_opportunity",
			Title:      "New opportunity",
			Body:       "A new opportunity matches your profile",
			CreatedAt:  "2026-04-24T01:30:00Z",
			UpdatedAt:  "2026-04-24T01:30:00Z",
			IsRead:     true,
			ActionText: "View opportunity",
			Data:       map[string]any{},
		},
		{
			UUID:       "5",
			UserUUID:   mockUserUUID,
			Type:       "new_message",
			Title:      "New message",
			Body:       "You have a new message",
			CreatedAt:  "2026-04-23T12:30:00Z",
			UpdatedAt:  "2026-04-23T12:30:00Z",
			IsRead:     true,
			ActionText: "View message",
			Data:       map[string]any{},
		},
		{
			UUID:       "6",
			UserUUID:   mockUserUUID,
			Type:       "shift_accepted",
			Title:      "Shift accepted",
			Body:       "Your shift request has been accepted",
			CreatedAt:  "2026-04-22T12:30:00Z",
			UpdatedAt:  "2026-04-22T12:30:00Z",
			IsRead:     true,
			ActionText: "View shift details",
			Data:       map[string]any{},
		},
		{
			UUID:       "7",
			UserUUID:   mockUserUUID,
			Type:       "new_message",
			Title:      "New message",
			Body:       "Message from Spindle team",
			CreatedAt:  "2026-04-22T12:30:00Z",
			UpdatedAt:  "2026-04-22T12:30:00Z",
			IsRead:     true,
			ActionText: "View message",
			Data:       map[string]any{},
		},
		{
			UUID:       "8",
			UserUUID:   mockUserUUID,
			Type:       "shifts_accepted",
			Title:      "Multiple shifts accepted",
			Body:       "Several shift requests have been accepted",
			CreatedAt:  "2026-04-21T12:30:00Z",
			UpdatedAt:  "2026-04-21T12:30:00Z",
			IsRead:     true,
			ActionText: "",
			Data:       map[string]any{},
		},
	}
}

